swagger: '2.0'
info:
  title: Crossref Metadata API
  description: Query Crossref metadata covering works, journals, publishers, funders and more.
  version: "1.0.0"
host: api.crossref.org
schemes:
  - https
  - http
basePath: /v1
produces:
  - application/json
paths:
  $ref: "./paths/index.yaml"
definitions:
  $ref: "./definitions/index.yaml"        
