swagger: '2.0'
info:
  title: Crossref Metadata API
  description: Query Crossref metadata covering works, journals, publishers, funders and more.
  version: "1.0.0"
host: api.crossref.org
schemes:
  - https
  - http
basePath: /v1
produces:
  - application/json
paths:
  /types:
  /types/{typeid}:
  /types/{typeid}/works:
    $ref: '#/getWorks'
  /works:
    $ref: '#/getWorks'
  /works/{doi}:
  /works/{doi}/agency:
  /works/{doi}/transform/{representation}:
  /works/{doi}.xml:
  /funders:
  /funders/{funderDoi}:
  /funders/{funderDoi}/works:
    $ref: '#/getWorks'
  /members:
  /members/{memberId}:
  /members/{memberId}/works:
    $ref: '#/getWorks'
  /prefixes:
  /prefixes/{doiPrefix}:
  /prefixes/{doiPrefix}/works:
    $ref: '#/getWorks'
  /journals:
  /journals/{issn}:
  /journals/{issn}/works:
    $ref: '#/getWorks'
  /licenses:
  
definitions:
  getWorks:
    tags:
      - Works
    parameters:
      - name: query
        type: string
        in: query
      - name: query.title
        type: string
        in: query
      - name: query.container-title
        type: string
      - name: query.author
        type: string
      - name: query.editor
        type: string
      - name: query.translator
        type: string
      - name: query.chair
        type: string
      - name: query.contributor
        type: string
      - name: filter
      - name: facet
      - name: sample
      - name: rows
      - name: offset
      - name: cursor
      - name: sort
      - name: order
        type: string
        enum: ["asc", "desc"]
    schema:
      $ref: '#/definitions/Work'

  QueryInformation:
    type: object
    required:
      - search-terms
      - start-index
    properties:
      search-terms:
        type: string
      start-index:
        type: integer

  FacetResults:
    type: object

  WorkMessage:
    type: object
    required:
      - status
      - message-type
      - message-version
      - message
    properties:
      status:
        type: string
        value: 'ok'
      message-type:
        type: string
        value: 'work'
      message-version:
        type: string
      message:
        $ref: '#/definitions/Work'

  WorkListMessage:
    type: object
    required:
      - status
      - message-type
      - message-version
      - message
    properties:
      status:
        type: string
        value: 'ok'
      message-type:
        type: string
        value: 'work-list'
      message-version:
        type: string
      message:
        $ref: '#/definitions/WorkList'

  WorkList:
    type: object
    required:
      - query
      - items-per-page
      - items
      - total-results
      - facets
    properties:
      query:
        $ref: '#/definitions/QueryInformation'
      items-per-page:
        type: integer
      total-results:
        type: integer
      items:
        type: array
        items:
          $ref: '#/definitions/Work'
      facets:
        $ref: '#/definitions/FacetResults'
        

  Work:
    type: object
    required:
      - publisher
      - title
      - reference-count
      - source
      - prefix
      - DOI
      - member
      - created
      - deposited
      - indexed
      - issued
    properties:
      publisher:
        type: string
      title:
        type: array
        items:
          type: string
      reference-count:
        type: number
      source:
        type: string
      prefix:
        type: string
      DOI:
        type: string
      member:
        type: string
      type:
        type: string
      created:
        $ref: '#/definitions/Date'
      deposited:
        $ref: '#/definitions/Date'      
      indexed:
        $ref: '#/definitions/Date'      
      issued:
        $ref: '#/definitions/PartialDate'
      subtitle:
        type: array
        items:
          type: string
      container-title:
        type: array
        items:
          type: string
      issue:
        type: string
      volume:
        type: string
      page:
        type: string
      article-nuber:
        type: string
      published-print:
        $ref: '#/definitions/PartialDate'
      published-online:
        $ref: '#/defintions/PartialDate'
      subject:
        type: array
        items:
          type: string
      ISSN:
        type: array
        items:
          type: string
      ISBN:
        type: array
        items:
          type: string
      archive:
        type: array
        items:
          type: string
      license:
        type: array
        items:
          $ref: '#/defintions/License'
      funder:
        type: array
        items:
          $ref: '#/definitions/Funder'
      assertion:
        type: array
        items:
          $ref: '#/definitions/Assertion'
      author:
        type: array
        items:
          $ref: '#/definitions/Contributor'
      editor:
        type: array
        items:
          $ref: '#/definitions/Contributor'
      chair:
        type: array
        items:
          $ref: '#/definitions/Contributor'
      translator:
        type: array
        items:
          $ref: '#/definitions/Contributor'
      update-to:
        type: array
        items:
          $ref: '#/definitions/Update'
      update-policy:
        type: string
      link:
        type: array
        items:
          $ref: '#/definitions/ResourceLink'
      clinical-trial-number:
        type: array
        items:
          $ref: '#/definitions/ClinicalTrialNumber'
      alternative-id:
        type: array
        items:
          type: string

  Funder:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      DOI:
        type: string
      award:
        type: array
        items:
          type: string
      doi-asserted-by:
        type: string
        enum: ['crossref', 'publisher']

  ClinicalTrialNumber:
    type: object
    required:
      - clinical-trial-number
      - registry
    properties:
      clinical-trial-number:
        type: string
      registry:
        type: string
      type:
        type: string
        enum: ['preResults', 'results', 'postResults']

  Contributor:
    type: object
    required:
      - family-name
    properties:
      family-name:
        type: string
      given-name:
        type: string
      ORCID:
        type: string
      affiliation:
        type: array
        items:
          $ref: '#/definitions/Affiliation'

  Affiliation:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  Date:
    type: object
    required:
      - date-parts
      - timestamp
      - date-time
    properties:
      date-parts:
        type: array
        items:
          type: integer
      timestamp:
        type: integer
      date-time:
        type: string

  PartialDate:
    type: object
    required:
      - date-parts
    properties:
      date-parts:
        type: array
        items:
          type: integer

  Update:
    type: object
    required:
      - updated
      - DOI
      - type
    properties:
      updated:
        $ref: '#/definitions/PartialDate'
      DOI:
        type: string
      type:
        type: string
      label:
        type: string
        
  Assertion:
    type: object
    required:
      - name
      - value
    properties:
      name:
        type: string
      value:
        type: string
      URL:
        type: string
      explanation:
        type: string
      label:
        type: string
      order:
        type: integer
      group:
        $ref: '#/definitions/AssertionGroup'

  AssertionGroup:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      label:
        type: string

  License:
    type: object
    required:
      - content-version
      - delay-in-days
      - start
      - URL
    properties:
      content-version:
        type: string
        enum: ['vor', 'am', 'tdm', 'unspecified']
      delay-in-days:
        type: integer
      start:
        $ref: '#/definitions/PartialDate'
      URL:
        type: string

  ResourceLink:
    type: object
    required:
      - intended-application
      - content-version
      - URL
    properties:
      intended-application:
        type: string
        enum: ['text-mining', 'unspecified']
      content-version:
        type: string
        enum: ['vor', 'am', 'tdm', 'unspecified']
      URL:
        type: string
      content-type:
        type: string
